name: thumbnailer
description: A new Flutter FFI plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.16.0<3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  ffi: ^1.1.2
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# flutter:

#   plugin:
#     platforms:
     
#       some_platform:
#         ffiPlugin: true