name: thumbnailer
description: A new Flutter FFI plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"
  flutter: ">=2.11.0-0.1.pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  ffi: ^0.1.3
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  plugin:
    platforms:
     
      some_platform:
        ffiPlugin: true