name: thumbnailer_example
description: Demonstrates how to use the thumbnailer plugin.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.16.0<3.0.0'
  # sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  # flutter:
  #   sdk: flutter

  thumbnailer:
    path: ../
  
  # cupertino_icons: ^1.0.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  # flutter_lints: ^1.0.0


flutter:
  uses-material-design: true